GET https://apis.data.go.kr/B551177/BusInformation/getBusInfo?serviceKey=%2Fk49W4UhNTuGlvyhZ6NCaHVhV1%2BBp0wbhWy0YjmvKgHQSFbVPwQqzw4ppSYg8O9ubHyLPYi8N%2F0e4yGvEQKGug%3D%3D&numOfRows=2&pageNo=1&area=1&type=json